---
- name: Send report
  hosts: localhost
  connection: local

  tasks:

    - name: Read VM report
      slurp:
        path: /tmp/vm_report.txt
      register: vm_report_file

    - name: Send email
      community.general.mail:
        host: "{{ smtp_server }}"
        port: "{{ smtp_port }}"
        username: "{{ email_user }}"
        password: "{{ email_pass }}"
        to: "{{ alert_recipient }}"
        subject: "VM Health Report"
        subtype: html
        body: |
          <h1>VM Health Report</h1>
          <pre>{{ vm_report_file.content | b64decode }}</pre>
