---
 - name: Collect metrics
  hosts: workers
  become: yes

  tasks:

    - name: Get CPU usage
      shell: "top -bn1 | grep 'Cpu(s)' | awk '{print 100 - $8}'"
      register: cpu

    - name: Get memory usage
      shell: "free | awk '/Mem/{printf(\"%.0f\", $3/$2 * 100)}'"
      register: mem

    - name: Get disk usage
      shell: "df / | awk 'NR==2 {print $5}' | tr -d '%'"
      register: disk

    - name: Store metrics
      set_fact:
        vm_metrics:
          hostname: "{{ inventory_hostname }}"
          cpu: "{{ cpu.stdout }}"
          mem: "{{ mem.stdout }}"
          disk: "{{ disk.stdout }}"
