# Auto-generated by Terraform

[control]
control-node ansible_host=${control_public_ip} ansible_user=ubuntu

[workers]
%{ for name, inst in instances ~}
${name} ansible_host=${inst.private_ip} ansible_user=ubuntu
%{ endfor ~}

[all:vars]
ansible_ssh_private_key_file=/home/ubuntu/kdmodder-ssh-key
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'